apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorel-dev
  labels:
    app: sorel-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorel-dev
  template:
    metadata:
      labels:
        app: sorel-dev
    spec:
      nodeSelector:
        homelab/role: core
      containers:
      - name: sorel-website
        image: ghcr.io/florentsorel/sorel.dev:f2c08d2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: sorel-dev
  labels:
    app: sorel-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sorel-dev
